name: flutter_boilerplate_tool
description: flutter_boilerplate_tool is a command-line utility designed to simplify the creation of boilerplate code for Flutter projects.
version: 1.0.2
repository: https://github.com/AbdulMoizWali/flutter_boilerplate_command_line_tool
homepage: https://github.com/AbdulMoizWali/flutter_boilerplate_command_line_tool

environment:
  sdk: '>=3.4.3 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.3.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0


executables:
  flutter_boilerplate_tool: flutter_boilerplate_tool

